# "https://bake.mavryk.org/"
baseURL: /
languageCode: "en-us"
title: "bake.mavryk.org"
sidebar_search_disable: false
copyright: "Mavryk Dynamics"

enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true

# Highlighting config
pygmentsCodeFences: true
pygmentsUseClasses: false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic: false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle: tango

# offline search with lunr
params:
  algolia_docsearch: false
  offlineSearch: true
  offlineSearchSummaryLength: 200
  offlineSearchMaxResults: 15

  github_project_repo: https://github.com/mavryk-network/bake.mavryk.org
  github_repo: https://github.com/mavryk-network/bake.mavryk.org_content
  github_branch: main
  path_base_for_github_subdir: "content"

  ui:
    feedback: # requires GA
      enable: false
      yes: Glad to hear it! Please <a href="https://github.com/mavryk-network/bake-mavryk-org-builder/issues/new">tell us how we can improve</a>.
      no: Sorry to hear that. Please <a href="https://github.com/mavryk-network/bake-mavryk-org-builder/issues/new">tell us how we can improve</a>.
    readingtime: 
      enable: false

  links:
    user:
      - name: Twitter
        url: https://twitter.com/MavrykDynamics
        icon: fab fa-twitter

    developer:
      - name: Github
        url: https://github.com/mavryk-network
        icon: fab fa-github
        desc: Development takes place here!

contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

staticDir:
  content/static

languages:
  en:
    description: Documentation
    languageName: English
    weight: 1

# menu:
#   main:
#     - name: "Home"
#       identifier: "home"
#       pre: "<i class='fa fa-home'></i>"
#       url: "/"
#       weight: 1
#     # - name: "Documentation"
#     #   identifier: "documentation"
#     #   pre: "<i class='fa fa-book'></i>"
#     #   url: "/documentation/"
#     #   weight: 0

module:
  hugoVersion:
    extended: true
    min: 0.100.0
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false