name: build docs 

on:
  repository_dispatch:
    types: ["subproject-updated"]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: klakegg/hugo:ext-alpine
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: recursive

      - name: mark safe
        run: |
          git config --global --add safe.directory '*'

      - name: collect tp docs
        run: |
          # command reference

          rm -rf content/injected/tezpay/cmd/*
          mkdir -p content/injected/tezpay/cmd/
          export CWD=$PWD
          cd projects/tezpay/docs/cmd
          for f in *.md; do
            echo "Processing $f file...";
            (echo "---";
            echo "title: $(printf $f | cut -d. -f1)";
            echo "weight: 3";
            echo "type: docs";
            echo "---") | \
            cat - $f > $CWD/content/injected/tezpay/cmd/$f
          done
          cd $CWD

          # configuration samples
          rm -rf content/injected/tezpay/configuration/*
          mkdir -p content/injected/tezpay/configuration/
          cd projects/tezpay/docs/configuration
          for f in config.*.hjson; do
            echo "Processing $f file...";
            (echo "---";
            echo "title: $(printf $f | cut -d. -f2)";
            echo "weight: 3";
            echo "type: docs";
            echo "summary: tezpay $(printf $f | cut -d. -f2) configuration";
            echo "---";
            echo '```yaml') | \
            cat - $f > $CWD/content/injected/tezpay/configuration/$(printf $f | cut -d. -f2).md
            (echo ''; echo '```') >> $CWD/content/injected/tezpay/configuration/$(printf $f | cut -d. -f2).md
          done
          cd $CWD
    
      - name: cleanup
        run: |
          rm -rf public/*
          rm -rf public/.git

      - name: build
        run: hugo

      - name: cname
        run: |
          printf docs.tez.capital > public/CNAME

      - name: Get current date
        id: date
        run: |
          echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          
      - name: publish
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_BUILDER_KEY }}
          GITHUB_SHA: $GITHUB_SHA 
        with:
          source-directory: public/
          destination-github-username: tez-capital
          destination-repository-name: docs.tez.capital
          user-email: docs-builder@tez.capital
          commit-message: publish-${{ steps.date.outputs.date }}
